// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int trigger1min_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int trigger1min = 10;
	/// <summary>PID: 500 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int httpaftergroup_500 = 500;
	/// <summary>PID: 500 | Type: read</summary>
	public const int httpaftergroup = 500;
	/// <summary>PID: 501 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int httpstatuscode_501 = 501;
	/// <summary>PID: 501 | Type: read</summary>
	public const int httpstatuscode = 501;
	/// <summary>PID: 510 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int httprequesturi_510 = 510;
	/// <summary>PID: 510 | Type: read</summary>
	public const int httprequesturi = 510;
	/// <summary>PID: 511 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int httprequestdata_511 = 511;
	/// <summary>PID: 511 | Type: read</summary>
	public const int httprequestdata = 511;
	/// <summary>PID: 520 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int httpresponsedata_520 = 520;
	/// <summary>PID: 520 | Type: read</summary>
	public const int httpresponsedata = 520;
	public class Write
	{
	}
}
public class WriteParameters
{
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Trigger1min_10 { get; set; }
	object Trigger1min { get; set; }
	object Httpaftergroup_500 { get; set; }
	object Httpaftergroup { get; set; }
	object Httpstatuscode_501 { get; set; }
	object Httpstatuscode { get; set; }
	object Httprequesturi_510 { get; set; }
	object Httprequesturi { get; set; }
	object Httprequestdata_511 { get; set; }
	object Httprequestdata { get; set; }
	object Httpresponsedata_520 { get; set; }
	object Httpresponsedata { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Trigger1min_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	public System.Object Trigger1min {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 500  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Httpaftergroup_500 {get { return GetParameter(500); }set { SetParameter(500, value); }}
	/// <summary>PID: 500  | Type: read</summary>
	public System.Object Httpaftergroup {get { return GetParameter(500); }set { SetParameter(500, value); }}
	/// <summary>PID: 501  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Httpstatuscode_501 {get { return GetParameter(501); }set { SetParameter(501, value); }}
	/// <summary>PID: 501  | Type: read</summary>
	public System.Object Httpstatuscode {get { return GetParameter(501); }set { SetParameter(501, value); }}
	/// <summary>PID: 510  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Httprequesturi_510 {get { return GetParameter(510); }set { SetParameter(510, value); }}
	/// <summary>PID: 510  | Type: read</summary>
	public System.Object Httprequesturi {get { return GetParameter(510); }set { SetParameter(510, value); }}
	/// <summary>PID: 511  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Httprequestdata_511 {get { return GetParameter(511); }set { SetParameter(511, value); }}
	/// <summary>PID: 511  | Type: read</summary>
	public System.Object Httprequestdata {get { return GetParameter(511); }set { SetParameter(511, value); }}
	/// <summary>PID: 520  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Httpresponsedata_520 {get { return GetParameter(520); }set { SetParameter(520, value); }}
	/// <summary>PID: 520  | Type: read</summary>
	public System.Object Httpresponsedata {get { return GetParameter(520); }set { SetParameter(520, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
